### ISSUE TITLE
Is there a place for communication?

### ISSUE THREAD

**Issue by hansonry** [noverd/SS13G#5]
Is there some kind of IRC or DISCORD or Matrix chat for communication? I am interested in helping out.

**Comment by noverd** [comment]
yes
my discord is CodTenAlt#9052

**Comment by noverd** [comment]
So are you interested in helping the project?

**Comment by hansonry** [comment]
Yeah! Sorry about not getting back to you. I'm working on a very dumb
prototype to understand how networking works in Godot. I wanted to start
working on the SS13G project with some idea of how networking works. And
then things got a little crazy in my life.

My discord I'd is: deaf_fish#5069

**Comment by noverd** [comment]
okay
